#!/usr/bin/python2.7
#r = requests.get(config.url + "false")
#r = requests.get(config.url + "true " + str(counter))
import requests
import time
from hosted import device, node, config

counter = 0
device.gpio.monitor(config.pin)
for (pin, state) in device.gpio.poll_forever():
    if state is True:
        counter += 1
        node.send('/counter:%d' % counter)
