#!/usr/bin/python2.7
import requests
import time
from hosted import device, node, config
config.restart_on_update()


device.gpio.monitor(config.pin)
for (pin, state) in device.gpio.poll_forever():
    deviceId = config.metadata['device_id']
    counter = 0
    while state == True:
        time.sleep(2) # to stabilize sensor
        if state == True:
            counter += 1
            r = requests.get(config.url + 'TRUE '+ str(counter) + str(deviceId))
            r = requests.get(config.url + str(pin))
            time.sleep(5) #to avoid multiple detection
            time.sleep(0.1) #loop delay, should be less than detection delay
        else:
            counter += 1
            r = requests.get(config.url + 'FALSE ' + str(counter) + str(deviceId))
